baseURL = "https://www.healyourselftoday.eu/"
languageCode = "en-us"
title = "Heal Yourself"
theme = "lodi"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Beatrix Berkics, Detoxification Specialist"
    description_photo = "portfolio.jpg"
    favicon = "favicon.ico"
    logo = "logo-2.png"
    email = "healyourselftoday@pm.me"
	facebook = "beatrixberkics"
    disclaimer ="atukaram"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "beatrix-avatar.jpg"
    intro = "About me"
    subtitle = "Let food be thy medicine and medicine be thy food."
    hero_right = " I am Beatrix. My journey started at the age of 12 years. I started to learn about nutrition, my body, myself till the present moment.  I Learned from inspiring, thriving people like Lou Corona, Dr. Morse and some others. There is a life force, a healing power that pervades nature, a force given to each and every one of us from birth by nature to keep us healthy and to heal us. Healing takes place from within out. Healing is detoxification and cellular regeneration. Nature cures when allowed to do so by removing the causes of enervation. Detox lets us get in touch with that true, original source of power within us. When you put living food into your system you will attract, create living life. <<You are what you eat!>> You attract what you are. The other side of healing arise from the body-mind-spirit connection. While you detox, it will effect your emotional state as much as your thoughts. We heal ourselves by letting go all the things which are holding us back from our own natural, vibrant, healthy being. Every experience is a lesson and an opportunity for us to grow and learn.  Healing is not a protocol. It’s an individual truth.  It's based on principles in life, self discovery. Never about the outside world, but to deconstruct the blockages and to be aligned with our own truth and integrity. "
    
[params.projects]
    enable = true
    title = "Health is your choice"
    subtitle = "Guidelines on a wonderful path"

[params.quotes]
    enable = true

[params.process]
    enable = false
    title = "Life-Flow"
    subtitle = "Integrate nature into daily human life"

[params.case_studies]
    enable = true
    title = "Services"
    subtitle = "Lifestyle Coaching to heal yourself"

[params.events]
    enable = true
    title = "Events"
    subtitle = "What am I doing, where and when"

[params.footer]
    enable = true
