baseURL = "https://gifted-bohr-bf9343.netlify.com/"
languageCode = "en-us"
title = "Heal Yourself"
theme = "lodi"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Beatrix Berkics, Detoxification Specialist"
    description_photo = "portfolio.jpg"
    favicon = "favicon.ico"
    logo = "logo-2.png"
    email = "beatrix.berkics@gmail.com"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "beatrix-avatar.jpg"
    intro = "About me"
    subtitle = "Let food be thy medicine and medicine be thy food."
    hero_right = ["I am Beatrice. I would like to help you to heal yourself. ",
    "My journey started at the age of 12 years, when I left animal products behind and started to learn about nutrition till the present moment. I Learned from inspiring, healthy  people like Lou Corona , Dr. Morse and many others.",
    "There is a life force, a healing power that pervades nature, a force given to each and every one of us from birth by nature to keep us healthy and to heal us. Healing takes place  from within out. Healing is detoxification and cellular regeneration, using herbs and raw living food. Detoxification is the only way to establish the homeostasis within the body. Nature cures when allowed to do so by removing the causes of enervation. Detox lets us get in touch with that true, original source of love within us.",
    "When you put living food into your system you will attract, create living life. 'You are what you eat'! The more you love yourself, the more raw, living food you eat, the better you will feel. You will change people around you. You attract what you are.", 
    "The other side of healing arise from the body-mind-spirit connection. While you detox it, will effect your emotional state as much as your thoughts. We heal ourselves by letting go all the things which are holding us back from our own natural, vibrant, healthy being. We are electrical, infinite beings with spirit. Every experience is a lesson and an opportunity for us to grow and learn. ", 
    "Are you ready for a change? It will take you to the place of radiant, healthy, and joyful life mentally, emotionally and physically!", 
    "All love emanates from self-love. Maintain an attitude of gratitude. Stay present to the beauty and love of living." 
    ]
    # hero_right = ["**Currently doing consultancy work at the region of Karlsruhe, Germany.", 
    # "The answer: Plants. The plant kingdom has everything we need.  I'm living proof.  [User Experience Society](https://www.facebook.com/UXSoc/)"
   #  ]
    # resume = "ResumeCollado.pdf"
[params.projects]
    enable = true
    title = "My Projects"
    subtitle = "Guidelines on a wonderful path"

[params.quotes]
    enable = true

[params.process]
    enable = false
    title = "Life-Flow"
    subtitle = "Integrate nature into daily human life"

[params.case_studies]
    enable = true
    title = "Services"
    subtitle = "Lifestyle Coaching based on Life-Flow"

[params.footer]
    enable = true
