baseURL = "https://gifted-bohr-bf9343.netlify.com/"
languageCode = "en-us"
title = "Heal Yourself"
theme = "lodi"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Alexis Collado, UX Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.ico"
    logo = "logo.png"
    email = "beatrix.berkics@gmail.com"
    #facebook = "lex.collado"
    #twitter = "lexiscollado"
    #dribbble = "alexiscollado"
    #linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"
    #medium = "ahvccollado"
    #github = "github"
    #googlescholar = "https://scholar.google.com/citations?user=XXXXXXXXXXXXXXXXXXXXX=en"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "beatrix-avatar.jpg"
    subtitle = "Hi! I'm Beatrix, a detox specialist, nutritionist and iridologist from Hungary."
    hero_right = ["**Currently doing consultancy work at the region of Karlsruhe, Germany.", 
    "For 30 years I did not eat one vegetable.  My parents tried all kinds of tricks to get me to eat them, but I wouldn't do it.  Who knew I would grow up to embrace a lifestyle eating raw and living foods consisting mostly of fruits and vegetables?!", 
    "My journey began over 6 years ago when, in my late 20's, I was diagnosed with several severe conditions. I had gone to the doctor for a routine check up because I notice my heart was racing even while resting.  It turns out I had high blood pressure and was on my way to heart disease. I was also pre-diabetic and had weak kidneys and a leaky gut.  Hearing that news got my attention.", 
    "Gradually I made dietary and lifestyle changes, began juicing, and detoxified my body.  I was always a body builder, but I lost 75 lbs of fat and re-built my body on plants--mostly fruits and superfoods. Most people ask me where I get my protein.", 
    "The answer: Plants. The plant kingdom has everything we need.  I'm living proof.  [User Experience Society](https://www.facebook.com/UXSoc/)"
    ]
    # resume = "ResumeCollado.pdf"

[params.process]
    enable = true
    title = "Life-Flow"
    subtitle = "Integrate nature into daily human life"

[params.case_studies]
    enable = true
    title = "Services"
    subtitle = "Lifestyle Coaching based on Life-Flow"

[params.footer]
    enable = true
